#pragma once

namespace fs = std::filesystem;

void cli_create_directories(const fs::path& path)
{
	std::error_code ec;

	fs::create_directories(path, ec);
}

std::string cli_path_to_string(const fs::path& path)
{
	return "\"" + path.generic_string() + "\"";
}

void cli_run(const std::vector<std::string>& arguments)
{
	if (arguments.size() != 1)
	{
		std::cout << "DTC: invalid command" << std::endl;

		return;
	}

	fs::path project_path = arguments[0];

	std::ifstream project_file(project_path);

	if (project_file.is_open() == false)
	{
		std::cout << "DTC: invalid project path: " << cli_path_to_string(project_path) << std::endl;

		return;
	}

	std::cout << "DTC: building project: " << cli_path_to_string(project_path) << std::endl;

	fs::path project_dir = project_path.parent_path();

	fs::path output_path_rel;

	project_file >> output_path_rel;

	fs::path output_path = project_dir / output_path_rel;

	fs::path output_dir = output_path.parent_path();

	cli_create_directories(output_dir);

	std::ofstream output_file(output_path);

	if (output_file.is_open() == false)
	{
		std::cout << "DTC: invalid output path: " << cli_path_to_string(output_path) << std::endl;

		return;
	}

	output_file << "// generated by DTC" << "\n\n";

	Compiler compiler;

	while (project_file.good())
	{
		fs::path source_file_path_rel;

		fs::path target_file_path_rel;

		project_file >> source_file_path_rel;

		if (source_file_path_rel.empty())
		{
			break;
		}

		project_file >> target_file_path_rel;

		fs::path source_file_path = project_dir / source_file_path_rel;

		fs::path target_file_path = project_dir / target_file_path_rel;

		std::ifstream source_file(source_file_path);

		if (source_file.is_open() == false)
		{
			std::cout << "DTC: invalid source path: " << cli_path_to_string(source_file_path) << std::endl;

			return;
		}

		cli_create_directories(target_file_path.parent_path());

		std::ofstream target_file(target_file_path);

		if (target_file.is_open() == false)
		{
			std::cout << "DTC: invalid target path: " << cli_path_to_string(target_file_path) << std::endl;

			return;
		}

		std::cout << "DTC: compiling dtl: " << cli_path_to_string(source_file_path_rel) << " -> " << cli_path_to_string(target_file_path_rel) << std::endl;

		std::ostringstream source_stream;

		source_stream << source_file.rdbuf();

		std::string source = std::move(source_stream).str();

		auto target = compiler.compile(source);

		target_file << "// generated by DTC from " << cli_path_to_string(source_file_path_rel) << "\n\n";

		target_file << target;

		fs::path target_path_from_output = fs::relative(target_file_path, output_dir);

		output_file << "#include " << cli_path_to_string(target_path_from_output) << '\n';
	}
}
